package model

import (
	"encoding/json"
	"time"

	"github.com/uptrace/bun"
)

type RecognitionDefect struct {
	bun.BaseModel `bun:"recognition_defects"`

	// DefectID is the primary key for this table; it is generated by client
	DefectID          string          `bun:"defect_id,pk" json:"defectId"`
	CreatedAt         *time.Time      `bun:"created_at,nullzero,default:current_timestamp" json:"createdAt"`
	UpdatedAt         *time.Time      `bun:"updated_at,nullzero" json:"updatedAt"`
	SessionID         string          `bun:"session_id,notnull" json:"sessionId"`
	AccountID         int             `bun:"account_id,nullzero" json:"accountId"`
	ImageURI          string          `bun:"image_uri" json:"imageUrl"`
	RecognitionResult json.RawMessage `bun:"recognition_result,notnull" json:"recognitionResult"`
	Environment       json.RawMessage `bun:"environment,notnull" json:"environment"`
}
