// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	// default value, leave for unknown
	MessageType_UNKNOWN MessageType = 0
	// ping-pong messages
	MessageType_PING MessageType = 1
	MessageType_PONG MessageType = 2
	// server push messages. start from 1 << 3
	/// uses MatrixUpdateMessage
	MessageType_MATRIX_DELTA_UPDATE_MESSAGE MessageType = 8
	/// uses MatrixUpdateMessage
	MessageType_MATRIX_ABSOLUTE_UPDATE_MESSAGE MessageType = 9
	// request-response pattern messages. start from 1 << 6
	/// uses MatrixUpdateSubscribeReq
	MessageType_MATRIX_UPDATE_SUBSCRIBE_REQ MessageType = 64
	/// uses MatrixUpdateSubscribeResp
	MessageType_MATRIX_UPDATE_SUBSCRIBE_RESP MessageType = 65
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "PING",
		2:  "PONG",
		8:  "MATRIX_DELTA_UPDATE_MESSAGE",
		9:  "MATRIX_ABSOLUTE_UPDATE_MESSAGE",
		64: "MATRIX_UPDATE_SUBSCRIBE_REQ",
		65: "MATRIX_UPDATE_SUBSCRIBE_RESP",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":                        0,
		"PING":                           1,
		"PONG":                           2,
		"MATRIX_DELTA_UPDATE_MESSAGE":    8,
		"MATRIX_ABSOLUTE_UPDATE_MESSAGE": 9,
		"MATRIX_UPDATE_SUBSCRIBE_REQ":    64,
		"MATRIX_UPDATE_SUBSCRIBE_RESP":   65,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Sequence int32   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Ping) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Sequence int32   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Pong) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Skeleton struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *Skeleton) Reset() {
	*x = Skeleton{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skeleton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skeleton) ProtoMessage() {}

func (x *Skeleton) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skeleton.ProtoReflect.Descriptor instead.
func (*Skeleton) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Skeleton) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

type MatrixUpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header                        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Segments []*MatrixUpdateMessage_Segment `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *MatrixUpdateMessage) Reset() {
	*x = MatrixUpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixUpdateMessage) ProtoMessage() {}

func (x *MatrixUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixUpdateMessage.ProtoReflect.Descriptor instead.
func (*MatrixUpdateMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MatrixUpdateMessage) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MatrixUpdateMessage) GetSegments() []*MatrixUpdateMessage_Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type MatrixUpdateSubscribeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Sequence int32   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are assignable to Id:
	//	*MatrixUpdateSubscribeReq_StageId
	//	*MatrixUpdateSubscribeReq_ItemId
	Id isMatrixUpdateSubscribeReq_Id `protobuf_oneof:"id"`
}

func (x *MatrixUpdateSubscribeReq) Reset() {
	*x = MatrixUpdateSubscribeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixUpdateSubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixUpdateSubscribeReq) ProtoMessage() {}

func (x *MatrixUpdateSubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixUpdateSubscribeReq.ProtoReflect.Descriptor instead.
func (*MatrixUpdateSubscribeReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MatrixUpdateSubscribeReq) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MatrixUpdateSubscribeReq) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (m *MatrixUpdateSubscribeReq) GetId() isMatrixUpdateSubscribeReq_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *MatrixUpdateSubscribeReq) GetStageId() int32 {
	if x, ok := x.GetId().(*MatrixUpdateSubscribeReq_StageId); ok {
		return x.StageId
	}
	return 0
}

func (x *MatrixUpdateSubscribeReq) GetItemId() int32 {
	if x, ok := x.GetId().(*MatrixUpdateSubscribeReq_ItemId); ok {
		return x.ItemId
	}
	return 0
}

type isMatrixUpdateSubscribeReq_Id interface {
	isMatrixUpdateSubscribeReq_Id()
}

type MatrixUpdateSubscribeReq_StageId struct {
	StageId int32 `protobuf:"varint,3,opt,name=stage_id,json=stageId,proto3,oneof"`
}

type MatrixUpdateSubscribeReq_ItemId struct {
	ItemId int32 `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3,oneof"`
}

func (*MatrixUpdateSubscribeReq_StageId) isMatrixUpdateSubscribeReq_Id() {}

func (*MatrixUpdateSubscribeReq_ItemId) isMatrixUpdateSubscribeReq_Id() {}

type MatrixUpdateSubscribeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Sequence int32   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *MatrixUpdateSubscribeResp) Reset() {
	*x = MatrixUpdateSubscribeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixUpdateSubscribeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixUpdateSubscribeResp) ProtoMessage() {}

func (x *MatrixUpdateSubscribeResp) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixUpdateSubscribeResp.ProtoReflect.Descriptor instead.
func (*MatrixUpdateSubscribeResp) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *MatrixUpdateSubscribeResp) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MatrixUpdateSubscribeResp) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type MatrixUpdateMessage_Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Bucket:
	//	*MatrixUpdateMessage_Segment_StageId
	//	*MatrixUpdateMessage_Segment_ItemId
	Bucket   isMatrixUpdateMessage_Segment_Bucket   `protobuf_oneof:"bucket"`
	Elements []*MatrixUpdateMessage_Segment_Element `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *MatrixUpdateMessage_Segment) Reset() {
	*x = MatrixUpdateMessage_Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixUpdateMessage_Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixUpdateMessage_Segment) ProtoMessage() {}

func (x *MatrixUpdateMessage_Segment) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixUpdateMessage_Segment.ProtoReflect.Descriptor instead.
func (*MatrixUpdateMessage_Segment) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 0}
}

func (m *MatrixUpdateMessage_Segment) GetBucket() isMatrixUpdateMessage_Segment_Bucket {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (x *MatrixUpdateMessage_Segment) GetStageId() int32 {
	if x, ok := x.GetBucket().(*MatrixUpdateMessage_Segment_StageId); ok {
		return x.StageId
	}
	return 0
}

func (x *MatrixUpdateMessage_Segment) GetItemId() int32 {
	if x, ok := x.GetBucket().(*MatrixUpdateMessage_Segment_ItemId); ok {
		return x.ItemId
	}
	return 0
}

func (x *MatrixUpdateMessage_Segment) GetElements() []*MatrixUpdateMessage_Segment_Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type isMatrixUpdateMessage_Segment_Bucket interface {
	isMatrixUpdateMessage_Segment_Bucket()
}

type MatrixUpdateMessage_Segment_StageId struct {
	StageId int32 `protobuf:"varint,1,opt,name=stage_id,json=stageId,proto3,oneof"`
}

type MatrixUpdateMessage_Segment_ItemId struct {
	ItemId int32 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3,oneof"`
}

func (*MatrixUpdateMessage_Segment_StageId) isMatrixUpdateMessage_Segment_Bucket() {}

func (*MatrixUpdateMessage_Segment_ItemId) isMatrixUpdateMessage_Segment_Bucket() {}

type MatrixUpdateMessage_Segment_Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//	*MatrixUpdateMessage_Segment_Element_StageId
	//	*MatrixUpdateMessage_Segment_Element_ItemId
	Id isMatrixUpdateMessage_Segment_Element_Id `protobuf_oneof:"id"`
	// amount: delta value under MATRIX_DELTA_UPDATE_MESSAGE,
	// absolute value under MATRIX_ABSOLUTE_UPDATE_MESSAGE
	Amount int32 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MatrixUpdateMessage_Segment_Element) Reset() {
	*x = MatrixUpdateMessage_Segment_Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixUpdateMessage_Segment_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixUpdateMessage_Segment_Element) ProtoMessage() {}

func (x *MatrixUpdateMessage_Segment_Element) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixUpdateMessage_Segment_Element.ProtoReflect.Descriptor instead.
func (*MatrixUpdateMessage_Segment_Element) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (m *MatrixUpdateMessage_Segment_Element) GetId() isMatrixUpdateMessage_Segment_Element_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *MatrixUpdateMessage_Segment_Element) GetStageId() int32 {
	if x, ok := x.GetId().(*MatrixUpdateMessage_Segment_Element_StageId); ok {
		return x.StageId
	}
	return 0
}

func (x *MatrixUpdateMessage_Segment_Element) GetItemId() int32 {
	if x, ok := x.GetId().(*MatrixUpdateMessage_Segment_Element_ItemId); ok {
		return x.ItemId
	}
	return 0
}

func (x *MatrixUpdateMessage_Segment_Element) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type isMatrixUpdateMessage_Segment_Element_Id interface {
	isMatrixUpdateMessage_Segment_Element_Id()
}

type MatrixUpdateMessage_Segment_Element_StageId struct {
	StageId int32 `protobuf:"varint,1,opt,name=stage_id,json=stageId,proto3,oneof"`
}

type MatrixUpdateMessage_Segment_Element_ItemId struct {
	ItemId int32 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3,oneof"`
}

func (*MatrixUpdateMessage_Segment_Element_StageId) isMatrixUpdateMessage_Segment_Element_Id() {}

func (*MatrixUpdateMessage_Segment_Element_ItemId) isMatrixUpdateMessage_Segment_Element_Id() {}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x43, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x43, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1f, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x2b, 0x0a, 0x08, 0x53, 0x6b,
	0x65, 0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0xe1, 0x02, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x08,
	0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0xee, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x08, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x4d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x5f, 0x0a, 0x07,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x42, 0x08, 0x0a,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x18, 0x4d, 0x61, 0x74, 0x72,
	0x69, 0x78, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x1b, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22,
	0x58, 0x0a, 0x19, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2a, 0xb6, 0x01, 0x0a, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x4d, 0x41,
	0x54, 0x52, 0x49, 0x58, 0x5f, 0x44, 0x45, 0x4c, 0x54, 0x41, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x08, 0x12, 0x22, 0x0a, 0x1e, 0x4d,
	0x41, 0x54, 0x52, 0x49, 0x58, 0x5f, 0x41, 0x42, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x45, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x09, 0x12,
	0x1f, 0x0a, 0x1b, 0x4d, 0x41, 0x54, 0x52, 0x49, 0x58, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x40,
	0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x41, 0x54, 0x52, 0x49, 0x58, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50,
	0x10, 0x41, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x6e, 0x65, 0x78, 0x74,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_messages_proto_goTypes = []interface{}{
	(MessageType)(0),                            // 0: MessageType
	(*Ping)(nil),                                // 1: Ping
	(*Pong)(nil),                                // 2: Pong
	(*Skeleton)(nil),                            // 3: Skeleton
	(*Header)(nil),                              // 4: Header
	(*MatrixUpdateMessage)(nil),                 // 5: MatrixUpdateMessage
	(*MatrixUpdateSubscribeReq)(nil),            // 6: MatrixUpdateSubscribeReq
	(*MatrixUpdateSubscribeResp)(nil),           // 7: MatrixUpdateSubscribeResp
	(*MatrixUpdateMessage_Segment)(nil),         // 8: MatrixUpdateMessage.Segment
	(*MatrixUpdateMessage_Segment_Element)(nil), // 9: MatrixUpdateMessage.Segment.Element
}
var file_messages_proto_depIdxs = []int32{
	4, // 0: Ping.header:type_name -> Header
	4, // 1: Pong.header:type_name -> Header
	4, // 2: Skeleton.header:type_name -> Header
	0, // 3: Header.type:type_name -> MessageType
	4, // 4: MatrixUpdateMessage.header:type_name -> Header
	8, // 5: MatrixUpdateMessage.segments:type_name -> MatrixUpdateMessage.Segment
	4, // 6: MatrixUpdateSubscribeReq.header:type_name -> Header
	4, // 7: MatrixUpdateSubscribeResp.header:type_name -> Header
	9, // 8: MatrixUpdateMessage.Segment.elements:type_name -> MatrixUpdateMessage.Segment.Element
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skeleton); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixUpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixUpdateSubscribeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixUpdateSubscribeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixUpdateMessage_Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixUpdateMessage_Segment_Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*MatrixUpdateSubscribeReq_StageId)(nil),
		(*MatrixUpdateSubscribeReq_ItemId)(nil),
	}
	file_messages_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*MatrixUpdateMessage_Segment_StageId)(nil),
		(*MatrixUpdateMessage_Segment_ItemId)(nil),
	}
	file_messages_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*MatrixUpdateMessage_Segment_Element_StageId)(nil),
		(*MatrixUpdateMessage_Segment_Element_ItemId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
