// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "AlvISs_Reimu",
            "url": "https://github.com/AlvISsReimu",
            "email": "alvissreimu@gmail.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/PenguinStats/api/v2/_private/result/matrix/{server}/{source}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Private"
                ],
                "summary": "Get DropMatrix",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server; default to CN",
                        "name": "server",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Global or Personal; default to global",
                        "name": "source",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shims.DropMatrixQueryResult"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/_private/result/pattern/{server}/{source}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Private"
                ],
                "summary": "Get PatternMatrix",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server; default to CN",
                        "name": "server",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Global or Personal; default to global",
                        "name": "source",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shims.PatternMatrixQueryResult"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/_private/result/trend/{server}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Private"
                ],
                "summary": "Get Trends",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server; default to CN",
                        "name": "server",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shims.TrendQueryResult"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/advanced": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Result"
                ],
                "summary": "Execute Advanced Query",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AdvancedQueryRequest"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/formula": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Formula"
                ],
                "summary": "Get Formula",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Get All Items",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/shims.Item"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "existence": {
                                                "$ref": "#/definitions/models.Existence"
                                            },
                                            "name_i18n": {
                                                "$ref": "#/definitions/models.I18nString"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/items/{itemId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Get an Item with ID",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/shims.Item"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "existence": {
                                            "$ref": "#/definitions/models.Existence"
                                        },
                                        "name_i18n": {
                                            "$ref": "#/definitions/models.I18nString"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid or missing itemId. Notice that this shall be the **string ID** of the item, instead of the internally used numerical ID of the item.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/notice": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notice"
                ],
                "summary": "Get All Notices",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Notice"
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/period": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EventPeriod"
                ],
                "summary": "Get All Event Periods",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/shims.Activity"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "existence": {
                                                "$ref": "#/definitions/models.Existence"
                                            },
                                            "label_i18n": {
                                                "$ref": "#/definitions/models.I18nString"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/report": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Submit an Item Drop Report",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/shims.ReportResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid or missing itemId. Notice that this shall be the **string ID** of the item, instead of the internally used numerical ID of the item.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/report/recall": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Recall an Item Drop Report",
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Invalid or missing itemId. Notice that this shall be the **string ID** of the item, instead of the internally used numerical ID of the item.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/report/recognition": {
            "post": {
                "description": "Submit an Item Drop Report with Frontend Recognition. Notice that this is a private API and is not designed for external use.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Bulk Submit with Frontend Recognition",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Item"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "existence": {
                                            "$ref": "#/definitions/models.Existence"
                                        },
                                        "keywords": {
                                            "$ref": "#/definitions/models.Keywords"
                                        },
                                        "name": {
                                            "$ref": "#/definitions/models.I18nString"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid or missing itemId. Notice that this shall be the **string ID** of the item, instead of the internally used numerical ID of the item.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/result/matrix": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Result"
                ],
                "summary": "Get DropMatrix",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server; default to CN",
                        "name": "server",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to query for personal drop matrix or not",
                        "name": "is_personal",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to show closed stages or not",
                        "name": "show_closed_zones",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma separated list of ark stage ids",
                        "name": "stageFilter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma separated list of ark item ids",
                        "name": "itemFilter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shims.DropMatrixQueryResult"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/result/pattern": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Result"
                ],
                "summary": "Get PatternMatrix",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server; default to CN",
                        "name": "server",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to query for personal pattern matrix or not",
                        "name": "is_personal",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shims.PatternMatrixQueryResult"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/result/trends": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Result"
                ],
                "summary": "Get Trends",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server; default to CN",
                        "name": "server",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/shims.TrendQueryResult"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/stages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stage"
                ],
                "summary": "Get All Stages",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/shims.Stage"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "code_i18n": {
                                                "$ref": "#/definitions/models.I18nString"
                                            },
                                            "existence": {
                                                "$ref": "#/definitions/models.Existence"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/stages/{stageId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stage"
                ],
                "summary": "Get an Stage with ID",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Stage ID",
                        "name": "stageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/shims.Stage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code_i18n": {
                                            "$ref": "#/definitions/models.I18nString"
                                        },
                                        "existence": {
                                            "$ref": "#/definitions/models.Existence"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid or missing stageId. Notice that this shall be the **string ID** of the stage, instead of the internally used numerical ID of the stage.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SiteStats"
                ],
                "summary": "Get Site Stats",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server; default to CN",
                        "name": "server",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/shims.SiteStats"
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/users": {
            "post": {
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Login with PenguinID",
                "deprecated": true,
                "parameters": [
                    {
                        "description": "User ID",
                        "name": "userId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/shims.SiteStats"
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/zones": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zone"
                ],
                "summary": "Get All Zones",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/shims.Zone"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "existence": {
                                                "$ref": "#/definitions/models.Existence"
                                            },
                                            "zoneName_i18n": {
                                                "$ref": "#/definitions/models.I18nString"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/PenguinStats/api/v2/zones/{zoneId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zone"
                ],
                "summary": "Get a Zone with ID",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zone ID",
                        "name": "zoneId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/shims.Zone"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "existence": {
                                            "$ref": "#/definitions/models.Existence"
                                        },
                                        "zoneName_i18n": {
                                            "$ref": "#/definitions/models.I18nString"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid or missing zoneId. Notice that this shall be the **string ID** of the zone, instead of the v3 API internally used numerical ID of the zone.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/v3/items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Get All Items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/models.Item"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "existence": {
                                                "$ref": "#/definitions/models.Existence"
                                            },
                                            "keywords": {
                                                "$ref": "#/definitions/models.Keywords"
                                            },
                                            "name": {
                                                "$ref": "#/definitions/models.I18nString"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/v3/items/{itemId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Get an Item with ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Item"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "existence": {
                                            "$ref": "#/definitions/models.Existence"
                                        },
                                        "keywords": {
                                            "$ref": "#/definitions/models.Keywords"
                                        },
                                        "name": {
                                            "$ref": "#/definitions/models.I18nString"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid or missing itemId. Notice that this shall be the **string ID** of the item, instead of the internally used numerical ID of the item.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/v3/stages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stage"
                ],
                "summary": "Get All Stages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/models.Stage"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "code": {
                                                "$ref": "#/definitions/models.I18nString"
                                            },
                                            "existence": {
                                                "$ref": "#/definitions/models.Existence"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/v3/stages/{stageId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stage"
                ],
                "summary": "Get an Stage with ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Stage ID",
                        "name": "stageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Stage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "$ref": "#/definitions/models.I18nString"
                                        },
                                        "existence": {
                                            "$ref": "#/definitions/models.Existence"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid or missing stageId. Notice that this shall be the **string ID** of the stage, instead of the internally used numerical ID of the stage.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/v3/zones": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zone"
                ],
                "summary": "Get All Zones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/models.Zone"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "existence": {
                                                "$ref": "#/definitions/models.Existence"
                                            },
                                            "name": {
                                                "$ref": "#/definitions/models.I18nString"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        },
        "/v3/zones/{zoneId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zone"
                ],
                "summary": "Get a Zone with ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zone ID",
                        "name": "zoneId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Zone"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "existence": {
                                            "$ref": "#/definitions/models.Existence"
                                        },
                                        "name": {
                                            "$ref": "#/definitions/models.I18nString"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid or missing zoneId. Notice that this shall be the **string ID** of the zone, instead of the internally used numerical ID of the zone.",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "$ref": "#/definitions/errors.PenguinError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.Extras": {
            "type": "object",
            "additionalProperties": true
        },
        "errors.PenguinError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "example": "INVALID_REQUEST"
                },
                "extras": {
                    "$ref": "#/definitions/errors.Extras"
                },
                "message": {
                    "type": "string",
                    "example": "invalid request: some or all request parameters are invalid"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "models.Existence": {
            "type": "object",
            "required": [
                "CN",
                "JP",
                "KR",
                "US"
            ],
            "properties": {
                "CN": {
                    "description": "CN: 国服 Mainland China Server (maintained by Hypergryph Network Technology Co., Ltd.)",
                    "$ref": "#/definitions/models.ServerExistence"
                },
                "JP": {
                    "description": "JP: 日服 Japan Server (maintained by Yostar Inc,.)",
                    "$ref": "#/definitions/models.ServerExistence"
                },
                "KR": {
                    "description": "KR: 韩服 Korea Server (maintained by Yostar Limited)",
                    "$ref": "#/definitions/models.ServerExistence"
                },
                "US": {
                    "description": "US: 美服/国际服 Global Server (maintained by Yostar Limited)",
                    "$ref": "#/definitions/models.ServerExistence"
                }
            }
        },
        "models.I18nOptionalString": {
            "type": "object",
            "properties": {
                "en": {
                    "description": "EN: English (en)",
                    "type": "string"
                },
                "ja": {
                    "description": "JP: 日本語 (ja)",
                    "type": "string"
                },
                "ko": {
                    "description": "KR: 한국어 (ko)",
                    "type": "string"
                },
                "zh": {
                    "description": "ZH: 中文 (zh-CN)",
                    "type": "string"
                }
            }
        },
        "models.I18nString": {
            "type": "object",
            "required": [
                "en",
                "ja",
                "ko",
                "zh"
            ],
            "properties": {
                "en": {
                    "description": "EN: English (en)",
                    "type": "string"
                },
                "ja": {
                    "description": "JP: 日本語 (ja)",
                    "type": "string"
                },
                "ko": {
                    "description": "KR: 한국어 (ko)",
                    "type": "string"
                },
                "zh": {
                    "description": "ZH: 中文 (zh-CN)",
                    "type": "string"
                }
            }
        },
        "models.Item": {
            "type": "object",
            "properties": {
                "existence": {
                    "description": "Existence is a map with server code as key and the existence of the item in that server as value.",
                    "type": "object"
                },
                "group": {
                    "description": "Group is an identifier of what the item actually is. For example, both orirock and orirock cube would have the same group, ` + "`" + `orirock` + "`" + `.",
                    "type": "string"
                },
                "itemId": {
                    "description": "ArkItemID (itemId) is the previously used, string form ID of the item; in JSON-representation ` + "`" + `itemId` + "`" + ` is used as key.",
                    "type": "string"
                },
                "keywords": {
                    "description": "Keywords is an arbitrary JSON object containing the keywords of the item, for optimizing the results of the frontend built-in search engine.",
                    "type": "object"
                },
                "name": {
                    "description": "Name is a map with language code as key and the name of the item in that language as value.",
                    "type": "object"
                },
                "penguinItemId": {
                    "description": "ItemID (penguinItemId) is the numerical ID of the item.",
                    "type": "integer"
                },
                "rarity": {
                    "type": "integer"
                },
                "sortId": {
                    "description": "SortID is the sort position of the item.",
                    "type": "integer"
                },
                "sprite": {
                    "description": "Sprite describes the location of the item's sprite on the sprite image, in a form of Y:X.",
                    "type": "string"
                }
            }
        },
        "models.Keywords": {
            "type": "object",
            "properties": {
                "alias": {
                    "description": "Alias of the item,",
                    "$ref": "#/definitions/models.I18nOptionalString"
                },
                "pron": {
                    "description": "Pronounciation hints of the item",
                    "$ref": "#/definitions/models.I18nOptionalString"
                }
            }
        },
        "models.Notice": {
            "type": "object",
            "properties": {
                "content_i18n": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "existence": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "severity": {
                    "$ref": "#/definitions/null.Int"
                }
            }
        },
        "models.ServerExistence": {
            "type": "object",
            "required": [
                "exist"
            ],
            "properties": {
                "endTime": {
                    "type": "integer"
                },
                "exist": {
                    "type": "boolean"
                },
                "startTime": {
                    "type": "integer"
                }
            }
        },
        "models.Stage": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is a map with language code as key and the code of the stage in that language as value.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "existence": {
                    "description": "Existence is a map with server code as key and the existence of the item in that server as value.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "extraProcessType": {
                    "description": "ExtraProcessType is the type of extra process that is used in the stage, e.g. \"GACHABOX\".",
                    "type": "string"
                },
                "minClearTime": {
                    "description": "MinClearTime is the minimum time (in milliseconds as a duration) it takes to clear the stage, referencing from prts.wiki",
                    "type": "number"
                },
                "penguinStageId": {
                    "description": "StageID (penguinStageId) is the numerical ID of the stage.",
                    "type": "integer"
                },
                "sanity": {
                    "description": "Sanity is the sanity requirement for a full clear of the stage.",
                    "type": "number"
                },
                "stageId": {
                    "description": "ArkStageID (stageId) is the previously used, string form ID of the stage; in JSON-representation ` + "`" + `stageId` + "`" + ` is used as key.",
                    "type": "string"
                },
                "stageType": {
                    "description": "StageType is the type of the stage, e.g. \"MAIN\", \"SUB\", \"ACTIVITY\" and \"DAILY\".",
                    "type": "string"
                },
                "zoneId": {
                    "description": "ZoneID is the numerical ID of the zone the stage is in.",
                    "type": "integer"
                }
            }
        },
        "models.Zone": {
            "type": "object",
            "properties": {
                "background": {
                    "description": "Background is the path of the background image of the zone, relative to the CDN endpoint.",
                    "type": "string"
                },
                "category": {
                    "description": "Category of the zone.",
                    "type": "string",
                    "example": "MAINLINE"
                },
                "existence": {
                    "description": "Existence is a map with server code as key and the existence of the item in that server as value.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "name": {
                    "description": "Name is a map with language code as key and the name of the item in that language as value.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "penguinZoneId": {
                    "description": "ZoneID is the numerical ID of the zone.",
                    "type": "integer"
                },
                "type": {
                    "description": "Type of the zone, e.g. \"AWAKENING_HOUR\" or \"VISION_SHATTER\". Optional and only occurres when ` + "`" + `category` + "`" + ` is \"MAINLINE\".",
                    "type": "string",
                    "example": "AWAKENING_HOUR"
                },
                "zoneId": {
                    "type": "string"
                }
            }
        },
        "null.Bool": {
            "type": "object",
            "properties": {
                "bool": {
                    "type": "boolean"
                },
                "valid": {
                    "description": "Valid is true if Bool is not NULL",
                    "type": "boolean"
                }
            }
        },
        "null.Int": {
            "type": "object",
            "properties": {
                "int64": {
                    "type": "integer"
                },
                "valid": {
                    "description": "Valid is true if Int64 is not NULL",
                    "type": "boolean"
                }
            }
        },
        "shims.Activity": {
            "type": "object",
            "properties": {
                "end": {
                    "$ref": "#/definitions/null.Int"
                },
                "existence": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "label_i18n": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "shims.DropInfo": {
            "type": "object",
            "properties": {
                "bounds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dropType": {
                    "type": "string"
                },
                "itemId": {
                    "type": "string"
                }
            }
        },
        "shims.DropMatrixQueryResult": {
            "type": "object",
            "properties": {
                "matrix": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shims.OneDropMatrixElement"
                    }
                }
            }
        },
        "shims.Item": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "existence": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "groupID": {
                    "type": "string"
                },
                "itemId": {
                    "type": "string"
                },
                "itemType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_i18n": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pron": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rarity": {
                    "type": "integer"
                },
                "sortId": {
                    "type": "integer"
                },
                "spriteCoord": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "shims.OneDrop": {
            "type": "object",
            "properties": {
                "itemId": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "shims.OneDropMatrixElement": {
            "type": "object",
            "properties": {
                "end": {
                    "$ref": "#/definitions/null.Int"
                },
                "itemId": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "stageId": {
                    "type": "string"
                },
                "start": {
                    "type": "integer"
                },
                "times": {
                    "type": "integer"
                }
            }
        },
        "shims.OneItemTrend": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "times": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "shims.OnePatternMatrixElement": {
            "type": "object",
            "properties": {
                "end": {
                    "$ref": "#/definitions/null.Int"
                },
                "pattern": {
                    "$ref": "#/definitions/shims.Pattern"
                },
                "quantity": {
                    "type": "integer"
                },
                "stageId": {
                    "type": "string"
                },
                "start": {
                    "type": "integer"
                },
                "times": {
                    "type": "integer"
                }
            }
        },
        "shims.Pattern": {
            "type": "object",
            "properties": {
                "drops": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shims.OneDrop"
                    }
                }
            }
        },
        "shims.PatternMatrixQueryResult": {
            "type": "object",
            "properties": {
                "pattern_matrix": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shims.OnePatternMatrixElement"
                    }
                }
            }
        },
        "shims.ReportResponse": {
            "type": "object",
            "properties": {
                "reportHash": {
                    "type": "string"
                }
            }
        },
        "shims.SiteStats": {
            "type": "object",
            "properties": {
                "totalApCost": {
                    "type": "integer"
                },
                "totalItemQuantities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shims.TotalItemQuantity"
                    }
                },
                "totalStageTimes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shims.TotalStageTime"
                    }
                },
                "totalStageTimes_24h": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shims.TotalStageTime"
                    }
                }
            }
        },
        "shims.Stage": {
            "type": "object",
            "properties": {
                "apCost": {
                    "type": "number"
                },
                "code": {
                    "type": "string"
                },
                "code_i18n": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dropInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shims.DropInfo"
                    }
                },
                "existence": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "minClearTime": {
                    "type": "number"
                },
                "recognitionOnly": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stageId": {
                    "type": "string"
                },
                "stageType": {
                    "type": "string"
                },
                "zoneId": {
                    "type": "string"
                }
            }
        },
        "shims.StageTrend": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/shims.OneItemTrend"
                    }
                },
                "startTime": {
                    "type": "integer"
                }
            }
        },
        "shims.TotalItemQuantity": {
            "type": "object",
            "properties": {
                "itemId": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "shims.TotalStageTime": {
            "type": "object",
            "properties": {
                "stageId": {
                    "type": "string"
                },
                "times": {
                    "type": "integer"
                }
            }
        },
        "shims.TrendQueryResult": {
            "type": "object",
            "properties": {
                "trend": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/shims.StageTrend"
                    }
                }
            }
        },
        "shims.Zone": {
            "type": "object",
            "properties": {
                "background": {
                    "type": "string"
                },
                "existence": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subType": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "zoneId": {
                    "type": "string"
                },
                "zoneIndex": {
                    "type": "integer"
                },
                "zoneName": {
                    "type": "string"
                },
                "zoneName_i18n": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "types.AdvancedQuery": {
            "type": "object",
            "required": [
                "server",
                "stageId"
            ],
            "properties": {
                "end": {
                    "$ref": "#/definitions/null.Int"
                },
                "interval": {
                    "$ref": "#/definitions/null.Int"
                },
                "isPersonal": {
                    "$ref": "#/definitions/null.Bool"
                },
                "itemIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "server": {
                    "type": "string"
                },
                "stageId": {
                    "type": "string"
                },
                "start": {
                    "$ref": "#/definitions/null.Int"
                }
            }
        },
        "types.AdvancedQueryRequest": {
            "type": "object",
            "required": [
                "queries"
            ],
            "properties": {
                "queries": {
                    "type": "array",
                    "maxItems": 5,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/types.AdvancedQuery"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "3.0.0-alpha.1",
	Host:        "https://penguin-stats.io",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "Penguin Statistics API",
	Description: "This is the Penguin Statistics v3 API, re-designed to aim for lightweight on wire.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
