name: Build Docker Image (Check)

on:
  # trigger on any pull requests
  pull_request:
    branches:
      - "**"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/golang@master
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --sarif-file-output=snyk.sarif

      # - name: Get Tag Version
      #   id: get_version
      #   run: |
      #     export TRUNCATED_GITHUB_SHA=$(echo ${{ github.sha }} | cut -c1-7);
      #     echo "VERSION=${GITHUB_REF/refs\/tags\//}+${TRUNCATED_GITHUB_SHA}" >> $GITHUB_ENV
      #     echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v1.14.1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false # for check workflow, we don't want to push
          tags: penguin-statistics/backend-next:${{ github.sha }}
